// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Map: typeof import('./src/components/Map.vue')['default']
    MapList: typeof import('./src/components/MapList.vue')['default']
  }
}

export {}
